### ISSUE TITLE
RangeError.

### ISSUE THREAD

**Issue by astroshim** [devappmin/flutter_heatmap_calendar#1]
Hello. 
I got following error when i run `HeatMap ` sample code.
Please let me know what i missed.

```
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building HeatMapPage(dirty):
RangeError (length): Invalid value: Not in inclusive range 0..268435455: -1

The relevant error-causing widget was: 

When the exception was thrown, this was the stack: 
#0      new _List (dart:core-patch/array.dart)
#1      List._allocateData (dart:core-patch/growable_array.dart:363:16)
#2      new _GrowableList (dart:core-patch/growable_array.dart:97:16)
#3      new _GrowableList.generate (dart:core-patch/growable_array.dart:131:20)
#4      new HeatMapColumn (package:flutter_heatmap_calendar/src/widget/heatmap_column.dart:135:20)
#5      HeatMapPage._heatmapColumnList (package:flutter_heatmap_calendar/src/widget/heatmap_page.dart:108:19)
#6      HeatMapPage.build (package:flutter_heatmap_calendar/src/widget/heatmap_page.dart:167:41)
#7      StatelessElement.build (package:flutter/src/widgets/framework.dart:4662:28)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (79 frames)
#90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#91     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#92     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (9 frames)
#101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3380:20)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#104    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#106    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#112    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#119    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#121    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#128    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#130    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#133    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#134    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#137    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#138    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#139    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#141    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#143    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#147    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#148    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#149    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#150    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#153    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#155    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#159    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#162    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#163    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#166    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#168    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#171    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#172    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#175    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#176    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#177    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#178    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#182    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#185    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#186    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#187    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#189    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#190    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#191    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#194    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#195    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#196    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#197    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#199    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#200    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#201    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#202    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#203    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#204    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#205    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#206    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================
```

**Comment by devappmin** [comment]
Thanks for informing me about this error!
I've fixed `RangeError` on version `1.0.3`.
